const SHORTMOVIES_DURATION = 40;

const SHOW_MORE_RES_1280_PLUS = 3;
const SHOW_MORE_RES_768 = 2;
const SHOW_MORE_320_480 = 2;

const USER_NAME_REGEXP = '^[A-Za-zА-Яа-яЁё /s -]+$';

const EMAIL_REGEXP = "[a-zA-Z0-9_.]+@[a-zA-Z0-9_]+\\.[a-z]{2,}";

export {
  SHORTMOVIES_DURATION,
  SHOW_MORE_RES_1280_PLUS,
  SHOW_MORE_RES_768,
  SHOW_MORE_320_480,
  USER_NAME_REGEXP,
  EMAIL_REGEXP,
};
